modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="newgame"
version="${mod_version}"
displayName="NewGame"
authors="jinyi"
description="Add newgame Button"

[[dependencies.newgame]]
modId="neoforge"
mandatory=true
versionRange="[21.1.169,)"
ordering="NONE"
side="BOTH"

[[dependencies.newgame]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"